from .in_memory_repositories import (
    InMemoryInvestmentDecisionRepository,
    InMemoryRecommendationProposalRepository,
    InMemoryRecommendationProposalVersionRepository,
    InMemoryRecommendationReasonRepository,
    InMemoryRecommendationSnapshotRepository,
    InMemoryRecommendationTraceRepository,
)
from .repository_protocols import (
    InvestmentDecisionRepositoryProtocol,
    RecommendationProposalRepositoryProtocol,
    RecommendationProposalVersionRepositoryProtocol,
    RecommendationReasonRepositoryProtocol,
    RecommendationSnapshotRepositoryProtocol,
    RecommendationTraceRepositoryProtocol,
)
from .sqlmodel_entities import (
    InvestmentDecisionEntity,
    RecommendationClaimLinkEntity,
    RecommendationEvidenceLinkEntity,
    RecommendationInputSnapshotEntity,
    RecommendationProposalEntity,
    RecommendationProposalVersionEntity,
    RecommendationReasonEntity,
)
from .sqlmodel_repositories import (
    SQLModelInvestmentDecisionRepository,
    SQLModelRecommendationProposalRepository,
    SQLModelRecommendationProposalVersionRepository,
    SQLModelRecommendationReasonRepository,
    SQLModelRecommendationSnapshotRepository,
    SQLModelRecommendationTraceRepository,
)

__all__ = [
    "RecommendationProposalRepositoryProtocol",
    "RecommendationProposalVersionRepositoryProtocol",
    "InvestmentDecisionRepositoryProtocol",
    "RecommendationTraceRepositoryProtocol",
    "RecommendationReasonRepositoryProtocol",
    "RecommendationSnapshotRepositoryProtocol",
    "InMemoryRecommendationProposalRepository",
    "InMemoryRecommendationProposalVersionRepository",
    "InMemoryInvestmentDecisionRepository",
    "InMemoryRecommendationTraceRepository",
    "InMemoryRecommendationReasonRepository",
    "InMemoryRecommendationSnapshotRepository",
    "SQLModelRecommendationProposalRepository",
    "SQLModelRecommendationProposalVersionRepository",
    "SQLModelInvestmentDecisionRepository",
    "SQLModelRecommendationTraceRepository",
    "SQLModelRecommendationReasonRepository",
    "SQLModelRecommendationSnapshotRepository",
    "RecommendationProposalEntity",
    "RecommendationProposalVersionEntity",
    "RecommendationInputSnapshotEntity",
    "RecommendationReasonEntity",
    "RecommendationClaimLinkEntity",
    "RecommendationEvidenceLinkEntity",
    "InvestmentDecisionEntity",
]
