from enum import Enum


class ProposalStatus(str, Enum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    SUPERSEDED = "SUPERSEDED"
    ARCHIVED = "ARCHIVED"


class DecisionState(str, Enum):
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    MODIFIED = "MODIFIED"
    DEFERRED = "DEFERRED"
    OVERRIDDEN = "OVERRIDDEN"


class RecommendationAction(str, Enum):
    BUY = "BUY"
    ADD = "ADD"
    HOLD = "HOLD"
    REDUCE = "REDUCE"
    SELL = "SELL"
    WATCH = "WATCH"
    REMOVE_FROM_WATCHLIST = "REMOVE_FROM_WATCHLIST"
    NO_ACTION = "NO_ACTION"


class ReasonType(str, Enum):
    THESIS_SUPPORT = "THESIS_SUPPORT"
    THESIS_CONTRADICTION = "THESIS_CONTRADICTION"
    VALUATION = "VALUATION"
    PORTFOLIO_CONSTRAINT = "PORTFOLIO_CONSTRAINT"
    RISK_CONTROL = "RISK_CONTROL"
    LIQUIDITY = "LIQUIDITY"
    EXECUTION = "EXECUTION"
    MONITORING = "MONITORING"
    PROVENANCE = "PROVENANCE"
    DATA_QUALITY = "DATA_QUALITY"
    RELATIONSHIP_SIGNAL = "RELATIONSHIP_SIGNAL"
    OPPORTUNITY_SIGNAL = "OPPORTUNITY_SIGNAL"


class RiskSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class MonitoringTriggerType(str, Enum):
    PRICE_MOVE = "PRICE_MOVE"
    THESIS_INVALIDATION = "THESIS_INVALIDATION"
    EVIDENCE_STALENESS = "EVIDENCE_STALENESS"
    CONCENTRATION_BREACH = "CONCENTRATION_BREACH"
    VOLATILITY_SPIKE = "VOLATILITY_SPIKE"
    LIQUIDITY_DETERIORATION = "LIQUIDITY_DETERIORATION"


class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    URGENT = "URGENT"


class RelationshipClass(str, Enum):
    SIMILARITY = "SIMILARITY"
    DEPENDENCY = "DEPENDENCY"
    COMPETITION = "COMPETITION"
    COMPLEMENTARITY = "COMPLEMENTARITY"
    HEDGE_DIVERSIFICATION = "HEDGE_DIVERSIFICATION"


class RelationshipType(str, Enum):
    COMPETITOR = "COMPETITOR"
    SUPPLIER = "SUPPLIER"
    CUSTOMER = "CUSTOMER"
    SUBSTITUTES = "SUBSTITUTES"
    COMPLEMENTS = "COMPLEMENTS"
    OWNS = "OWNS"
    DEPENDS_ON = "DEPENDS_ON"
    BENEFITS_FROM = "BENEFITS_FROM"
    REPLACES = "REPLACES"
    THREATENS = "THREATENS"
    LICENSES = "LICENSES"
    ACQUIRES = "ACQUIRES"
    INVESTS_IN = "INVESTS_IN"
    POWERED_BY = "POWERED_BY"
    MANUFACTURES = "MANUFACTURES"
    ENABLES = "ENABLES"
    HEDGE_FOR = "HEDGE_FOR"


class OpportunityType(str, Enum):
    THEME_ROTATION = "THEME_ROTATION"
    SUPPLY_CHAIN_DISLOCATION = "SUPPLY_CHAIN_DISLOCATION"
    VALUATION_DISPERSION = "VALUATION_DISPERSION"
    HEDGE_SETUP = "HEDGE_SETUP"
    EVENT_DRIVEN = "EVENT_DRIVEN"


class ConfidenceDimension(str, Enum):
    COMPANY_QUALITY = "COMPANY_QUALITY"
    VALUATION_ATTRACTIVENESS = "VALUATION_ATTRACTIVENESS"
    PORTFOLIO_SUITABILITY = "PORTFOLIO_SUITABILITY"
    RECOMMENDATION_CONFIDENCE = "RECOMMENDATION_CONFIDENCE"
    RELATIONSHIP_CONFIDENCE = "RELATIONSHIP_CONFIDENCE"
    EXPECTED_RETURN = "EXPECTED_RETURN"


class TraceExecutionStatus(str, Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class TraceEntryType(str, Enum):
    INPUT_SNAPSHOT_REFERENCE = "INPUT_SNAPSHOT_REFERENCE"
    THESIS_HEALTH_INPUT = "THESIS_HEALTH_INPUT"
    PORTFOLIO_SUITABILITY_INPUT = "PORTFOLIO_SUITABILITY_INPUT"
    RISK_WARNING_EVALUATION = "RISK_WARNING_EVALUATION"
    STRATEGY_EVALUATION = "STRATEGY_EVALUATION"
    SCORING_COMPONENT_RESULT = "SCORING_COMPONENT_RESULT"
    CONFIDENCE_COMPONENT_RESULT = "CONFIDENCE_COMPONENT_RESULT"
    ACTION_SELECTION = "ACTION_SELECTION"
    POSITION_SIZE_RANGE_DERIVATION = "POSITION_SIZE_RANGE_DERIVATION"
    EXECUTION_CONSIDERATION_DERIVATION = "EXECUTION_CONSIDERATION_DERIVATION"
    MONITORING_TRIGGER_DERIVATION = "MONITORING_TRIGGER_DERIVATION"
    FINAL_PROPOSAL_ASSEMBLY = "FINAL_PROPOSAL_ASSEMBLY"
    VALIDATION_RESULT = "VALIDATION_RESULT"
    EXECUTION_FAILURE = "EXECUTION_FAILURE"


class TraceEntryStatus(str, Enum):
    APPLIED = "APPLIED"
    SKIPPED = "SKIPPED"
    FAILED = "FAILED"


class RuleResult(str, Enum):
    PASSED = "PASSED"
    FAILED = "FAILED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class RuleSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
